### ISSUE TITLE
Request: add nodes_save_frames node

### ISSUE THREAD

**Issue by ShmuelRonen** [jeffy5/comfyui-faceless-node#7]
Hello and thanks for yours important work!

You have a node name nodes_load_frames for converting video to images. It might help a lot if you make a reverse node nodes_save_frames that receives frames and converts it to a video format.

Are it possible?

**Comment by jeffy5** [comment]
In face, there is a node called FacelessSaveVideo which will merge all frames to generate a video. Do you want a separate node that merges frames and audio from a specific directory?

**Comment by ShmuelRonen** [comment]
> In face, there is a node called FacelessSaveVideo which will merge all frames to generate a video. Do you want a separate node that merges frames and audio from a specific directory?

This is a simulation that explain the nodes_save_frames node: 
![simulation1](https://github.com/jeffy5/comfyui-faceless-node/assets/80190186/43d247c9-2dd1-460d-8aaf-8ba0a34504c1)
